name: Node.js CI

on:
  push:
    branches: 
      - main
    paths:
      - 'path/to/your/bot/files/**'  # Replace this with the specific path where your bot files are located
  pull_request:
    branches: 
      - main
    paths:
      - 'path/to/your/bot/files/**'  # Same here, specify the bot files path
  workflow_dispatch:  # Allows manual triggering from GitHub Actions interface

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Step to check out the repository code
    - uses: actions/checkout@v2

    # Step to set up the specified Node.js version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    # Step to install dependencies
    - name: Install dependencies
      run: npm install

    # Step to start the bot (optional, only if you need it to run automatically)
    - name: Start the bot
      env:
        PORT: 8080
      run: npm start
